base16.lua:
  filename: lua/tinted-nvim/palettes/{{ scheme-system }}-{{ scheme-slug }}.lua
  supported-systems: [base16]

base16.vim:
  filename: colors/{{ scheme-system }}-{{ scheme-slug }}.vim
  supported-systems: [base16]

base24.lua:
  filename: lua/tinted-nvim/palettes/{{ scheme-system }}-{{ scheme-slug }}.lua
  supported-systems: [base24]

base24.vim:
  filename: colors/{{ scheme-system }}-{{ scheme-slug }}.vim
  supported-systems: [base24]
